### ISSUE TITLE
Add copy-paste checker for ZoKrates code

### ISSUE THREAD

**Issue by fulldecent** [EYBlockchain/nightfall#50]
Some code in this repository is copy-pasted from ZoKrates. This is important code which affects the security of the system. The upstream code could be changed at any time (possibly in response to a known security issue) without notification to this project. This has happened once already at (https://github.com/EYBlockchain/nightfall/issues/14). This issue increases the information security assurance of Nightfall by removing this lack of notification.

# Work plan

- [x] Identify which files are copy-pasted and should be checked
- [ ] Create an automated test. Add functionality:
  - [ ] Download latest file from ZoKrates (either from master or latest released version).
  - [ ] Compare that file to the file in this repository.
  - [ ] Create an error if they are not identical (possibly ignoring certain comments in the header).
- [ ] Add the test to our test suite.
- [ ] Add the test suite to Travis automated testing.
- [ ] Publish the result of Travis automated testing as a badge in README.md.

# Affected files

- AddressUtils.sol - [from 0xcert](https://github.com/0xcert/ethereum-erc721/blob/master/src/contracts/utils/address-utils.sol) (lacking attribution)
- ERC165.sol - from 0xcert
- ERC20Interface.sol - from 0xcert
- ERC721Interface.sol - from 0xcert
- ERC721Metadata.sol - from 0xcert
- ERC721TokenReceiver.sol - from 0xcert
- FToken.sol - from zOS
- GM17_lib_v0.sol - from Christian Reitwiessner
- GM17_v0.sol - from Christian Reitwiessner
- NFToken.sol - from 0xcert
- NFTokenMetadata.sol - from 0xcert (MODIFIED)
- Ownable.sol - [from 0xcert](https://github.com/0xcert/ethereum-erc721/blob/master/src/contracts/ownership/ownable.sol) (lacking attribution)
- Pairing_v1.sol - from Mustafa Al-Bassam and Christian Reitwiessner
- Points.sol - from Christian Reitwiessner (lacking attribution)
- SafeMath.sol - [from old version of OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/9aa30e19605e686d324448645c6594d2d31464c6/contracts/math/SafeMath.sol) (lacking attribution)
- SupportsInterface.sol - [from 0xcert](https://github.com/0xcert/ethereum-erc721/blob/master/src/contracts/utils/supports-interface.sol) (lacking attribution)

**Comment by ronbeilinson** [comment]
Hey @fulldecent,

Hey, any update on this security check? Definitely sounds like a great idea so let me know if you are stuck or having trouble.

Have you thought of integrating GitHub Actions instead of Travis? In terms of level of comfort with either tool, I believe GitHub Actions would be my preferred option.  I'll create an issue for this and will keep you updated on when it is ready for tests to be added, though I assume it's similar to Travis (update yaml, etc). Let me know if you have any questions or need help with this.

**Comment by fulldecent** [comment]
Reference: here is one copy-paste validator -- https://github.com/su-squares/ethereum-contract/blob/master/test/confirm-sol-merged.sh

**Comment by fulldecent** [comment]
Updated top comment to now show all files which are in scope for copy-paste testing. In the meantime I have identified missing attributions here and then at upstream I have found some issues/potential improvements which have been reported to the respective projects.

**Comment by ChaitanyaKonda** [comment]
The zokrates interface has been abstracted to this [repo](https://github.com/EYBlockchain/zokrates.js.git). And this library doesn't have any zokrates code.

But the updates for the affected files suggested here should be checked for
