### ISSUE TITLE
Too many workflow technologies

### ISSUE THREAD

**Issue by fulldecent** [EYBlockchain/nightfall#78]
Currently several technologies are used for starting/stopping/testing the application:

* Docker Compose
* Docker (from inside zkp module)
* npm scripts running in Docker client environment (in package.json)
* npm scripts running on host environment
* Bash scripts (e.g. install.sh)
* Makefile
* Python (I can't find where though)
* AppleScript (only if running on macOS)

I recommend to reduce this to two on the host machine:

* Docker Compose
* Makefile

The end result would be that it is possible to generate keys, install, run and test the application all using Docker Compose commands (which are initiated from the Makefile). This removes many steps from the install process and many prerequisites from all people using the software.

From INSIDE the docker container or on a development machine having all required prerequisites, the following technologies could be used:

* npm scripts (i.e. `npm test` and `npm install`)

---

# Work plan

- [ ] Remove all node_modules folders from the repository
- [ ] Remove any use of `npm install` from the host environment (i.e. only use npm inside Docker)
- [ ] Refactor install.sh into the Makefile
- [ ] Refactor zkp-demo into the Makefile
- [ ] Refactor zkp-demo-test into the Makefile
- [ ] Separate the prerequisites section into those needed for running versus those needed for developing

# Discussion

I have been studying the key generation workflow for a while and am not sure yet if we can get good performance on that by running it entirely in Docker.

The adoption of Docker will also allow tighter prerequesites to be set. e.g. Node 12 can be specified for some modules and Node 10 for others. This should hopefully remove the need for Babel.
